name: Test PR

on: pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create testing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: testing

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Container build test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: false
          tags: ${{ github.repository }}:latest
          platforms: linux/amd64
